dist: trusty
language: cpp
sudo: false
os: "linux"
compiler:
  - gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-6
    - libsfml-dev
env:
  - CFLAGS=-Wall CXXFLAGS=-std=c++14 CXX=g++-6
script:
  - make bld/gui
