dist: artful
language: cpp
sudo: false
os: "linux"
compiler:
- gcc
env:
- CFLAGS=-Wall CXXFLAGS=-std=c++17
before_install:
- sudo apt-get -qq update
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get -qq update
- sudo apt-get install -y gcc-7
- sudo apt-get install -y libsfml-dev
install:
- export CXX="g++-7"
before_script:
- curl "https://raw.githubusercontent.com/philsquared/Catch/master/single_include/catch.hpp" -o inc/catch.hpp 
script:
- make bld/gui
- make bld/test
