language: cpp
compiler:
  - gcc
sudo: required
os: "linux"
arch:
  packages:
    - gcc
    - cmake
    - sfml
  script:
    - mkdir build
    - cd build
    - cmake -DBUILD_TESTS=ON ..
    - make
before_script:
  - curl "https://raw.githubusercontent.com/philsquared/Catch/master/single_include/catch.hpp" -o include/catch.hpp 
script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
