dist: trusty
language: cpp
sudo: false
os: "linux"
compiler:
  - gcc
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-6"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-6
    - libsfml-dev
env:
  - CFLAGS=-Wall CXXFLAGS=-std=c++14 
script:
  - make bld/gui
